### ISSUE TITLE
SORMAS ÖGD Entity-relationship diagram

### ISSUE THREAD

**Issue by MallerBeach** [hzi-braunschweig/SORMAS-Glossary#25]
Dear all,

recently, the IT of the health office of Bremen, rolled out SORMAS ÖGD. 
 
Currently, I am trying to understand the structure of the data obtained via the statistics export.  Using the R-scripts of https://github.com/hzi-braunschweig/SORMAS-Stats and looking at the data is helpful but not more than a good guess and of course a lack of personal exchange with HZI ist kind of a barrier. 

Setting up https://github.com/hzi-braunschweig/SORMAS-Glossary/tree/master/schemaspy is a little bit challenging as we do do not have access to the backend of SORMAS.

Do we have to use https://github.com/hzi-braunschweig/SORMAS-Docker to create a local instance of SORMAS?

**Comment by JonasCir** [comment]
@MallerBeach Thanks for opening the issue! I think we can sort this out :)

**Comment by JonasCir** [comment]
@MallerBeach Thanks for opening the issue (close was unintentional)! I think we can sort this out :) 
@Candice-Louw Do you still have the shared drive where I uploaded the schema spy zip?

**Comment by JonasCir** [comment]
In general I would suggest to setup SORMAS-Docker as it is the most convenient way to spin up and play around with SORMAS.
The quick start [instructions](https://github.com/hzi-braunschweig/SORMAS-Docker#quick-start) are all you need to do.

**Comment by bernardsilenou** [comment]
@JonasCir  @MallerBeach  I also think it is better to setup a local instance.

**Comment by Candice-Louw** [comment]
@MallerBeach - if you'd like a SchemaSpy document of the database in HTML format (webpage) as generated for 1.56.1 by @JonasCir, you're welcome to download it here: :)

**Comment by MallerBeach** [comment]
@Candice-Louw @JonasCir Great stuff! Hopefully this will help those working at local administrations for whom the installation of docker can may be a bit of a burden due to a lack of admin rights : ) 

Anyway, docker should be the preferred solution.

@bernardsilenou Thank you for pointing me in the right direction at first place.

**Comment by MallerBeach** [comment]
Dear all, would it be possible to provide to current version of the SchemaSpy? As major changes regarding vaccinations took place, I am a bit lost.

**Comment by JonasCir** [comment]
@Candice-Louw Can you share the ZIP?

**Comment by Candice-Louw** [comment]
@MallerBeach - could you please send me your details? I'll gladly share the new schema that JonasCir generated!

**Comment by Candice-Louw** [comment]
Scheme shared on 15.12.2021. Issue to incorporate this into the release process going forward: https://github.com/hzi-braunschweig/SORMAS-Project/issues/5585
